README.md

According to the PHP-FIG (http://www.php-fig.org/), some PHP implementations need to be standardized.

Change documentation according to the PSR-2

---

README.md

Fixed single quote issue on line 418

Fixed single quote issue on line 418

---

README.md

Added info how to use templates.

Added templating documentation

---

lib/SendGrid.php
lib/SendGrid/Email.php
lib/SendGrid/Exception.php
lib/SendGrid/Response.php

I'm using the SendGrid API, and SDK actively in my daily work.
I'd propose a couple changes to make it more consistent formatting wise. 
I'd also like to do some further adjustments later.

Updating code to make a bit more consistent

---

lib/SendGrid.php

When using a proxy, this is really useful to set a timeout.

added timeout option

---

USE_CASES.md

Update USE_CASES.md to include Attachments

---

CONTRIBUTING.md

fix link to ISSUE_TEMPLATE

---

README.md

fix Readme SendGrid Logo

---

CONTRIBUTING.md
lib/loader.php
test/unit/bootstrap.php

Hoping to make getting started easier for the non-composer people out there.

Updating docs and non-composer includes

---

USAGE.md
examples/suppression/suppression.php

Change spam_report() to spam_reports() in documentation and examples

---

CODE_OF_CONDUCT.md

This is referent to issue #455.
I've used the doc example you provided at the issue description

Added Code OF conduct into root of project

---

USE_CASES.md

docs(php): Add doc for setting up domain whitelabel

---

LICENSE.txt

Updated MIT LICENSE.

---

test/unit/FilesExistTest.php

Add unit test to check that specific files exist in repository.

Add unittest to check that specific files exist in repo

---

.github/ISSUE_TEMPLATE

Added the latest stable released version - PHP 7.2.x
- 
- 

Update PHP Version terms

---

test/unit/FilesExistTest.php
test/unit/GenericTest.php

Corrected the broken unit tests.

Fix broken unit tests

---

lib/mail/Mail.php

Fixes #619 
- Improved PHPdoc warnings
- Improve code style & self assignments

PHPDoc & code improvements

---

lib/mail/EmailAddress.php
lib/mail/Mail.php

Remaining cleanup items from PR #620

---

lib/mail/Mail.php

Fix for #629

---

lib/mail/EmailAddress.php

Fixed wrong Exception namesapce

---

lib/mail/Attachment.php

Fix base64 bug

---

README.md

#768 
On the website its mentioned that Send up to 40,000 emails for 30 days, then send 100 emails/day free forever but it has not been mentioned in the README.

 Updations in prerequisites #768

---

examples/helpers/mail/example.php

Fixes #792 
Added missing example of how to use personalization index.

Update example.php. Add personalization example as per #792

---

USAGE.md
examples/templates/templates.php

- I have added tests that prove my fix is effective or that my feature works
- I have added in line documentation to the code I modified
- Update USAGE.md for retrieving a list of all templates (dynamic & legacy)
- Update /example file for retrieving a list of all templates (dynamic & legacy)

docs: Update documentation for retrieving a list of all templates

---

.github/workflows/test-and-deploy.yml
README.md

Added a deploy job to the test and deploy GitHub Action workflow that creates a new GitHub release when run for tags. Updated build status badge and Slack notification to cover deployments by the workflow.

chore: add deploy job to test and deploy gh workflow

---

composer.json

Updated php-http-client version to enable setHost
If you have questions, please file a [support ticket](https://support.sendgrid.com).

chore: updated php-http-client version to enable setHost
