lib/SendGrid.php
I noticed that the **turn_off_ssl_verification** option was no longer working in the latest version. I tracked the bug down with the switch to cURL. Under the hood it was directly using the value of **turn_off_ssl_verification** to set the cURL flag **CURLOPT_SSL_VERIFYPEER** but they actually have the opposite boolean meaning.
CURLOPT_SSL_VERIFYPEER
- FALSE to stop cURL from verifying the peer's certificate. Alternate certificates to verify against can be specified with the CURLOPT_CAINFO option or a certificate directory can be specified with the CURLOPT_CAPATH option.
Reference: http://php.net/manual/en/function.curl-setopt.php (CURLOPT_SSL_VERIFYPEER)
=> Fixes the turn_off_ssl_verification option so that it works with cURL.

lib/SendGrid.php
This request would help you to fix a nasty bug - limitations which do not allow to send email with multiple bcc.
When we add multiple bcc, we get a multidimensional array and an error :
[php] Array to string conversion
in:
vendor/sendgrid/sendgrid/lib/SendGrid.php:51
=> Fix limitations which do not allow to send email with multiple bcc

README.md
In the documentation it says that starting versio 3.2.0 addTo should not be called more than once. However, in the example it does just that. So I propose we remove that second line to avoid confusion, no?
=> The addTo should only be called ONCE

.gitignore, composer.json, test/unit/SendGridTest.php
Version 3.2.0 and above from the `sendgrid/php-http-client` library use improved autoloading, fixing a problem where `\SendGrid\Response` cannot be found when using a non-optimized composer installation.
When semantic versioning is applied, it is save to upgrade to newer feature releases.
=> Upgrade sendgrid/php-http-client

lib/SendGrid.php, test/unit/SendGridTest.php
In order to allow proxies and curl specific options. Should fix #345
=> Allow passing curlOptions to the client

scripts/s3upload.sh
if you require the sendgrid-php.php (Non-composer version) in a background process you would have relative path problems. Full path solves this problem.
=> Relative path fix for background jobs (Issue #352)

test/unit/SendGridTest.php
As per the Node.js, Python and Ruby implementations
=> Typo 'user' for 'usr'

.gitignore, lib/helpers/mail/Mail.php
Closes #332 and probably #314.
=> Fixed serialization of empty JSON objects.

composer.json, lib/SendGrid.php, test/unit/SendGridTest.php
This PR add a curlOptions option to merge custom parameters to curl, and add the ability to set a proxy and/or a timeout.
Should be merged after:
https://github.com/sendgrid/php-http-client/pull/11
=> added support to extend curl options

lib/helpers/mail/Mail.php
custom args can *only* be strings per SendGrid support otherwise a 400 bad request will be returned
=> API level addressing of the string-only custom arg rule

README.md, USAGE.md, USE_CASES.md, examples/accesssettings/accesssettings.php, examples/alerts/alerts.php, examples/apikeys/apikeys.php, examples/asm/asm.php, examples/browsers/browsers.php, examples/campaigns/campaigns.php, examples/categories/categories.php, examples/clients/clients.php, examples/contactdb/contactdb.php, examples/devices/devices.php, examples/geo/geo.php, examples/helpers/mail/example.php, examples/ips/ips.php, examples/mail/mail.php, examples/mailboxproviders/mailboxproviders.php, examples/mailsettings/mailsettings.php, examples/partnersettings/partnersettings.php, examples/scopes/scopes.php, examples/senders/senders.php, examples/stats/stats.php, examples/subusers/subusers.php, examples/suppression/suppression.php, examples/templates/templates.php, examples/trackingsettings/trackingsettings.php, examples/user/user.php, examples/whitelabel/whitelabel.php
Avoids:
```
PHP Notice:  Array to string conversion
```
=> Use `print_r` instead of `echo` on Arrays.

mail-helper-refactor.md
I think you had a very small typo in one of the examples (adding $to instead of the ToCollection $tos).
=> Fixed minor typo during Mail creation

mail-helper-refactor.md
Collections should be optional. Not all OOP frameworks utilize collections. Nor people who wan't to create a procedural script.
=> Refactoring: Removal of collections

TROUBLESHOOTING.md
Wasn't sure how to phrase it while keeping it simple.
[Explanation of issue and fix](https://github.com/sendgrid/sendgrid-php/issues/371#issuecomment-335913858)
> If you were to have a file like this:
> 
> `.sendgrid`: (notice the linebreak)
> ```
> SG.**
> 
> ```
> and you used it like
> ```php
> $apiKey = file_get_contents('.sendgrid');
> $sendgrid = new \SendGrid($apiKey);
> $sendgrid->client->mail()->send()->post($message);
> ```
> 
> The raw HTTP request, sent by curl, would look like: (notice the linebreak)
> ```
> POST /v3/mail/send
> Host: api.sendgrid.com
> Authorization: Bearer SG.**
> 
> User-Agent: sendgrid/*;php
> Accept: application/json
> Content-Type: application/json
> ```
> 
> This causes all the headers after the `Authorization` header to be treated as the message body …
=> Add TROUBLESHOOTING.md section about fixing error 415

USE_CASES.md
Condenses the comments on the header and adds composer as recommended source of the library.
Relates to discussion on #441.
=> Changes the recommendation to use composer as recommended source

test/unit/SendGridTest.php
Incorrect documentation path fixed.
Pending traces to SendGridTest.php fixed.
=> Incorrect documentation path fixed. Issue #336

README.md
=> Moved logo on top and added twitter and contributors badges

examples/mail/mail.php, test/unit/SendGridTest.php
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
"Tag omission: Must have a start tag and must not have an end tag."
=> Don't close <img> tag in HTML

mail-helper-refactor.md
Semicolon are expected after instructions.
=> Fix syntax error in refactor documentation

.codeclimate.yml
closes #524 
Feature
----------------------------------------------------------
Add codeclimate
Installation
------------------------------------------------------------
- If you haven't already, install the [Code Climate CLI](https://github.com/codeclimate/codeclimate).
- Run codeclimate engines:enable phpmd
- This command both installs the engine and enables it in your .codeclimate.yml
- You're ready to analyze!
- Browse into your project's folder and run codeclimate analyze
- Specific language test, for instance, php run codeclimate analyze -e phpmd
=> Created code climate YML file

test/unit/SendGridTest.php
Fixes #532 .
Simple unit test to verify if the license file contains the end year as the current one
=> Add license date range unit test

.travis.yml
- Adds support for CodeCov as mentioned in #541 
I haven't checked everything on the list as it wasn't really relevant. I've tested the commit in my Travis CI instance though.
- [Travis Build](https://travis-ci.org/pxgamer/sendgrid-php/builds/294983325)
- [CodeCov](https://codecov.io/github/pxgamer/sendgrid-php/commit/7204c8087e3fc75130e4c29a4ad060b391ccb510)
=> Added CodeCov support

TROUBLESHOOTING.md, USE_CASES.md
Adds `php.ini` file instructions to both files `USE_CASES.md` and `TROUBLESHOOTING.md`
Fixes #423
@thinkingserious please review.
=> Adding Google App engine installation with composer instructions

lib/helpers/mail/Mail.php
API level addressing of the string-only in addSubstitution arg rule.   Every long integer triggers a bad request.
- 
- 
=> Bad Request

USE_CASES.md
Per http://php.net/manual/en/language.basic-syntax.phptags.php it's best to
omit PHP closing tags when a code file is pure PHP to avoid to accidentally
send whitelines to the buffer output, before headers could be sent.
As such, documentation should not use closing tags to reflect best practices.
=> Omit PHP closing tag in use case sample

lib/helpers/mail/Mail.php, test/unit/Mail/MailHelperTest.php
This PR fixes issue #368 and replaces #370. It wraps the email name in double quotes when commas or semicolons are present (without, the mail would be rejected by the API).
I've added unit test to check the behavior of the `Sendgrid\Email->setName()` method. I've also sent real emails with various names to verify that they are delivered.
I've also added a comment explaining the issue because the patch should be reverted if the API is modified to support commas and semicolons.
=> Add support for commas and semicolons in email name and add test

lib/mail/Attachment.php, test/unit/Attachments.php, test/unit/KitchenSinkTest.php
Fixes #611 
- When an attachement is added it first checks whether or not it has already been base64 encoded, if not it encodes its.
=> Attachments now automatically get base64 encoded if they are not already

lib/mail/GroupsToDisplay.php, test/unit/KitchenSinkTest.php
Fixes #624: Fix setGroupsToDisplay's handling of array arguments
=> Fix setGroupsToDisplay's handling of array arguments

phpcs.xml
Fixes #610 
There would seem to be a couple of possible fixes:
phpcs.xml file included in this pull request includes the PSR2 ruleset from: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR2/ruleset.xml
The whitespace at the end of lines rule has been removed. Not sure whether to include this or not but with this rule in place there are a huge number of whitespace errors. Please see gist of phpcs output: https://gist.github.com/hjmsw/aa5e0608fa38acaeb9c5a6f6a1aa788d
And without whitespace at end of line rule, another gist:
https://gist.github.com/hjmsw/2ac4f13a0b92dad296369481d0cf872e
Another alternative would be to use the `--standard=PSR2` command switch when running phpcs. The rules wanting to be ignored in #610 were ignored when I ran with the above command …
=> Potential fix for: Remove unnecessary linter warning from phpcs

README.md, USAGE.md, USE_CASES.md, lib/loader.php
The following changes relate to use in a non-composer environment:
* Add missing file extension for `/mail/BatchId` in `loader.php`
* Re-order requires to ensure `EmailAddress` is loaded before `Bcc` (`Bcc` depends on `EmailAddress` being loaded)
* Change `README.md` to reference `./lib/loader.php` instead of `./sendgrid-php.php` for non-composer use.
* Change example documentation to reference the required HTTP library dependency and how to install it without composer
NOTE: It is likely that the `use` commands in https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates can be removed as well.
=> The following changes relate to use in a non-composer environment:

examples/accesssettings/accesssettings.php, examples/alerts/alerts.php, examples/apikeys/apikeys.php, examples/asm/asm.php, examples/browsers/browsers.php, examples/campaigns/campaigns.php, examples/categories/categories.php, examples/clients/clients.php, examples/contactdb/contactdb.php, examples/devices/devices.php, examples/geo/geo.php, examples/helpers/contacts/recipients.php, examples/helpers/mail/example.php, examples/ips/ips.php, examples/mail/mail.php, examples/mailboxproviders/mailboxproviders.php, examples/mailsettings/mailsettings.php, examples/partnersettings/partnersettings.php, examples/scopes/scopes.php, examples/senders/senders.php, examples/stats/stats.php, examples/subusers/subusers.php, examples/suppression/suppression.php, examples/templates/templates.php, examples/trackingsettings/trackingsettings.php, examples/user/user.php, examples/whitelabel/whitelabel.php
Fixes #617
Adds try / catch for all call examples in /examples
=> Add try / catch to examples. Fixes #617

README.md, USE_CASES.md
- Corrects a syntax error in documentation example
=> Corrected PHP Syntax

README.md
=> updated Readme tag

lib/SendGrid.php, test/unit/SendGridTest.php
Sendgrid API has a feature allowing parent accounts to impersonate
subusers by including an HTTP header "On-Behalf-Of" in each API request.
This commit enables setting the value for impersonation when creating
the Sendgrid API Client instance, through the `$options` argument.
Fixes #551
=> Add ability to impersonate subuser

CHANGELOG.md, lib/mail/Attachment.php
=> isBase64 function fix

lib/mail/DynamicTemplateData.php, lib/mail/Mail.php, lib/mail/Personalization.php, test/unit/KitchenSinkTest.php
- Adds dynamic template support by adding a new helper object, new methods into the mail and personalization classes.
=> Allow for Dynamic Templates Implementation

test/prism.sh
=> Update prism version. Fixes #690

USE_CASES.md, composer.json
Resolves #481 
- Updates USE_CASES.md with an example of how to attach a file from Box to an email.
=> Added Box attachment example (issue #481)

lib/mail/EmailAddress.php, test/unit/MailHelperTest.php
The next condition on line 73 is wrong (file /mail/EmailAddress.php).
if (!is_string($emailAddress) && filter_var($emailAddress, FILTER_VALIDATE_EMAIL))
It turns out that email address shouldn't be a string and should be a valid address simultaneously in order to throw exception.
Probably the right condition is:
if (!(is_string($emailAddress) && filter_var($emailAddress, FILTER_VALIDATE_EMAIL)))
=> Fixes #739 Wrong condition

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md
- Update CONTRIBUTING - contribution guideline to branch off development
=> Update CONTRIBUTING - contribution guideline to branch off development

scripts/package.sh, test/prism.sh
Hello,
In my opinion, No GIT_VERSION variable are required.
And, Use of` "``" is not recommended.
Ref: http://mywiki.wooledge.org/BashFAQ/082
https://stackoverflow.com/questions/4708549/what-is-the-difference-between-command-and-command-in-shell-programming	 
What do you think of it?
Thanks.
- 
- 
=> clean up shell script

lib/mail/Mail.php
Fixes #669 
Updates the `Mail::setGlobalSubject()` to match inline documentation.
=> Fix Mail::setGlobalSubject()

.travis.yml, sendgrid-php.php, test/prism.sh
- Added support for 7.3 in Travis.yml
- Update the Prism script so that it does not fail when it can't find the latest version number
=> PHP 7.3 support and fix Prism download problem

lib/mail/EmailAddress.php
- [X ] I acknowledge that all my contributions will be made under the project's license
- [X ] I have read the [Contribution Guide] and my PR follows them.
Change the exception message from single quotes to double quotes so the user will know which email address failed.
=> Make $emailAddress on TypeException to be evaluated

lib/mail/Mail.php
Fixes #788 
Fixed missing parameter issue. Allows adding CC/BCC when passing a $personalizationIndex.
Example usage also included in KitchenSink example in another pull request: https://github.com/sendgrid/sendgrid-php/pull/836
=> Fixes #788  - Add missing parameter for addCc and addBcc methods

examples/mail/mail.php
- Tweaks a link in the mail readme (currently 404s)
=> fix: correct the mail helper readme link in example

TROUBLESHOOTING.md
=> fix: update the link for cURL example in Troubleshooting.MD

README.md
Fixed path to License file on ReadMe
Fixed path to License file on ReadMe
- Fixed path to License file on ReadMe
=> fix: correct the License file path in ReadMe

docker/README.md
We shouldn't need to run Docker as root if it's been installed
correctly, and the user is already part of the `docker` group.
If this was not the case, we would've required other steps to be run
with `sudo`.
=> docs: remove `sudo` requirement for running docker

examples/helpers/mail/example.php
Fixed an example code in example.php which had a wrong params order. Both `From` and `To` extend from `EmailAddress` where `$emailAddress` is the first param (name second and optional)
https://github.com/sendgrid/sendgrid-php/blob/a8468b65dc4a9f1eff25936df79dd587177f4338/lib/mail/EmailAddress.php#L47-L51
=> docs: correct params order in example.php

lib/mail/Attachment.php, lib/mail/Mail.php, test/unit/MailHelperTest.php
Fixes https://github.com/sendgrid/sendgrid-php/issues/614
Fixes https://github.com/sendgrid/sendgrid-php/issues/616
Fixes https://github.com/sendgrid/sendgrid-php/issues/819
Fixes https://github.com/sendgrid/sendgrid-php/issues/873
Fixes https://github.com/sendgrid/sendgrid-php/issues/849
Fixes https://github.com/sendgrid/sendgrid-php/issues/607
=> fix: refactor and fix personalization inserts/updates

USAGE.md
Add documentation for "Retrieve recipients matching search criteria using segment conditions"; Enhanced similar documentation for "Create Segment".
=> docs: add documentation for segments in USAGE.md

composer.json, lib/BaseSendGridClientInterface.php, lib/SendGrid.php, lib/TwilioEmail.php, lib/loader.php
Fixes #964
Using such a common class name in a global namespace may cause collisions with other projects.
=> fix: Rename 'BaseInterface' to 'BaseSendGridClientInterface.php'

.gitignore, composer.json, examples/helpers/eventwebhook/example.php, lib/eventwebhook/EventWebhook.php, lib/eventwebhook/EventWebhookHeader.php, lib/loader.php, test/unit/EventWebhookTest.php
When enabling the "Signed Event Webhook Requests" feature in Mail Settings, Twilio SendGrid will generate a private and public key pair using the Elliptic Curve Digital Signature Algorithm (ECDSA). Once that is successfully enabled, all new event posts will have two new headers: X-Twilio-Email-Event-Webhook-Signature and X-Twilio-Email-Event-Webhook-Timestamp, which can be used to validate your events.
This SDK update will make it easier to verify signatures from signed event webhook requests by using the VerifySignature method. Pass in the public key, event payload, signature, and timestamp to validate. Note: You will need to convert your public key string to an elliptic public key object in order to use the VerifySignature method.
=> feat: verify signature from event webhook

docker/Dockerfile, lib/SendGrid.php, test/unit/SendGridTest.php
- At my job, we have a facade API that sits in between consumers and SendGrid; it does some various things that are important to our business. We overrode the host which worked fine, but it also added /v3 to the end, so that our URLs ended up being _http://company-email-api.domain.com/api/v1/email/v3_. 
- I thought this was a simple update to give users more flexibility and should be fully backwards compatible.
- I also updated a couple pieces of the Dockerfile; The URL for prism bash script was a 404, so I updated to the current existing install script. I also added support for dos2unix, which coverts line endings. My host machine is windows, and I had lots of issues getting the docker container to run for tests because of line endings.
- I didn't apt-get remove dos2linux because I still …
=> feat: Add an option to override SendGrid Client path version

lib/mail/EmailAddress.php, lib/mail/Mail.php, lib/stats/Stats.php, test/unit/MultipleEmailToMultipleRecipientsTest.php
If a specific 'to' address is "personalized" (contains substitutions or a subject), it should be in a new personalization object since a single personalization object cannot contain mixed substitutions or subjects.
Fixes #998
=> fix: support 'to' addresses with subjects

lib/mail/EmailAddress.php, test/unit/EmailAddressTest.php
The backend has been updated (reference _MP-4337_) to properly handling names with special characters so the original "fix" is no longer needed.
Reverts https://github.com/sendgrid/sendgrid-php/pull/511
Fixes #897
=> fix: don't wrap names in double-quotes

USE_CASES.md
The file type and file name are in the wrong order for the $attachments array used in addAttachments. Used that way, files do not attach properly.
=> docs: Incorrect value order in example array for addAttachments

lib/BaseSendGridClientInterface.php, lib/SendGrid.php, lib/TwilioEmail.php
- Allows the ability for a user to utilise self-signed certificates with SendGrid
- Current Client implementation will fail to process a `curl_init()` function if, for example, the user is testing the implementation on a local server with an unknown CA
- See [PR here](https://github.com/sendgrid/php-http-client/pull/101)
=> feat: Allows for a user to utilize self-signed certificates

test/unit/AsmTest.php, test/unit/BatchIdTest.php, test/unit/BccSettingsTest.php, test/unit/BypassListManagementTest.php, test/unit/CategoryTest.php, test/unit/ClickTrackingTest.php, test/unit/ContentTest.php, test/unit/CustomArgTest.php, test/unit/FooterTest.php, test/unit/GanalyticsTest.php, test/unit/GroupIdTest.php, test/unit/HeaderTest.php, test/unit/HtmlContentTest.php, test/unit/IpPoolNameTest.php, test/unit/MailTest.php, test/unit/OpenTrackingTest.php, test/unit/PersonalizationTest.php, test/unit/PlainTextContentTest.php, test/unit/SandBoxModeTest.php, test/unit/SectionTest.php, test/unit/SendAtTest.php, test/unit/SpamCheckTest.php, test/unit/SubjectTest.php, test/unit/SubscriptionTrackingTest.php, test/unit/TemplateIdTest.php, test/unit/TrackingSettingsTest.php
Fixing some classes namespaces and they should be `SendGrid\Tests\Unit` namespace.
If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.
=> fix: Fixing namespace for classes on test/unit folder

USAGE.md, USE_CASES.md, examples/helpers/mail/example.php, examples/mail/mail.php, lib/mail/BypassBounceManagement.php, lib/mail/BypassSpamManagement.php, lib/mail/BypassUnsubscribeManagement.php, lib/mail/Mail.php, lib/mail/MailSettings.php, test/integration/Mail/MailSendTest.php, test/unit/BypassBounceManagementTest.php, test/unit/BypassSpamManagementTest.php, test/unit/BypassUnsubscribeManagementTest.php, test/unit/KitchenSinkTest.php
https://docs.sendgrid.com/ui/sending-email/index-suppressions#bypass-filters-and-v3-mail-send
https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send
=> feat: add spam, bounce and unsubscribe bypass management filters

lib/mail/Mail.php
I found that the function description did not match the way it works.
It's a small contribution but houses always built with a small bricks
=> docs: rewrite function description

USE_CASES.md, examples/dataresidency/setregion.php, lib/BaseSendGridClientInterface.php, test/unit/DataResidencyTest.php
Adding data residency with global as the default region and adding support for eu region as well.
If you have questions, please file a [support ticket](https://support.sendgrid.com).
=> feat: Added Data residency for eu and global region

.github/workflows/test-and-deploy.yml, .gitignore, Makefile, prism.sh
Docker-compose v2 is default for github actions now. So using it here also
If you have questions, please file a [support ticket](https://support.sendgrid.com).
=> chore: install docker-compose
